### ISSUE TITLE
Agent with GraphCypherQAChain tool failed to save into memory.

### ISSUE THREAD

**Issue by miquelmongeAZ** [neo4j-graphacademy/llm-chatbot-python#6] opened 2024-02-07 11:32 UTC
By following the course "[Build a Neo4j-backed Chatbot using Python](https://graphacademy.neo4j.com/courses/llm-chatbot-python/)", when running the code the agent enters into the cypher_qa tool and generates the cypher code to query the database.

The problem is that when saving into memory it trows the following error:
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for AIMessage
content
  str type expected (type=type_error.str)
content
  value is not a valid list (type=type_error.list)

It is this a bug, the code is out-of-day as per the langchain verison?

**Comment by AntoninJuquel** [comment] 2024-02-27 12:06
Looks like a duplicate of [issue-4](https://github.com/neo4j-graphacademy/llm-chatbot-python/issues/4)

But here is my answer on how i solved it:

> Hello I solved this issue by settting `return_direct=False` and adding `handle_parsing_error=True` to every tools in the `agent.py` file. Here is my tools list with the changes:
> 
> ```python
> tools = [
>     Tool.from_function(
>         name="General Chat",
>         description="For general chat not covered by other tools",
>         func=llm.invoke,
>         return_direct=False, # (!)
>         handle_parsing_errors=True # (!)
>     ),
>     Tool.from_function(
>         name="Cypher QA",
>         description="Provide information about movies questions using Cypher",
>         func = cypher_qa,
>         return_direct=False, # (!)
>         handle_parsing_errors=True # (!)
>     ),
>     Tool.from_function(
>         name="Vector Search Index",
>         description="Provides information about movie plots using Vector Search",
>         func = kg_qa,
>         return_direct=False, # (!)
>         handle_parsing_errors=True # (!)
>     )
> ]
> ```
> 
> Here is the result:
> 
> ![image](https://private-user-images.githubusercontent.com/57025128/308157562-a4802068-5aac-41ae-bf43-1ac2aa44e837.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzU2NzgsIm5iZiI6MTcwOTAzNTM3OCwicGF0aCI6Ii81NzAyNTEyOC8zMDgxNTc1NjItYTQ4MDIwNjgtNWFhYy00MWFlLWJmNDMtMWFjMmFhNDRlODM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyMDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Yjk3ZWI3MDVkZjYwNjEyMzJlMjRlNDYyODc5MTQ5NmQ1OTFhOWMxMjI1MjA2MjliZmYyZDA2MTgxZGU4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJH5z4UYkaMy95Olzd5zog9TlU8v7kueYq77evPOQ-g)
> 
> ![image](https://private-user-images.githubusercontent.com/57025128/308157779-af9db39f-6a07-465e-8bb3-e5eaea63f687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzU2NzgsIm5iZiI6MTcwOTAzNTM3OCwicGF0aCI6Ii81NzAyNTEyOC8zMDgxNTc3NzktYWY5ZGIzOWYtNmEwNy00NjVlLThiYjMtZTVlYWVhNjNmNjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEyMDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTQwZmY2ZjdlMWI1NGVhOWFjNTdkYjY2ODZmNzRkNTJhZWQyYzk5NzRjODEwMjM1Y2E0ZDg1NjUwYTRjZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u18hxeRgqibWCazjnCxgcmk19xWKNXj2CgWMaxhVahU)

**Comment by martinohanlon** [comment] 2024-06-18 11:22
Thanks for raising the issue. 

The course has been recently updated to reflect changes in Langchain v0.2 and the code to manage agents and tools updated.

Closing as no longer relevant.

**Closed as completed by martinohanlon** 2024-06-18 11:22 UTC
